# Generated by Django 5.0.6 on 2024-07-29 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0002_rename_order_salesinvoice_sales'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesitem',
            name='stock_snapshop',
            field=models.IntegerField(null=True),
        ),
    ]
