# Generated by Django 5.0.6 on 2024-08-09 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0005_customer_created_by_paymentreceived_created_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salesinvoice',
            name='payment_status',
            field=models.CharField(choices=[('Paid', 'Paid'), ('Unpaid', 'Unpaid'), ('Partial', 'Partial')], default='Unpaid', max_length=20),
        ),
    ]
