# Generated by Django 5.0.6 on 2024-08-15 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0006_alter_salesinvoice_payment_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentreceived',
            name='transaction_id',
            field=models.CharField(max_length=100),
        ),
    ]
