# Generated by Django 5.0.6 on 2024-09-12 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0007_alter_paymentreceived_transaction_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='sales',
            name='Returned sales',
            field=models.BooleanField(default=False),
        ),
    ]
