# Generated by Django 5.0.6 on 2024-06-20 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0001_initial'),
        ('tenant', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BaseUserOfMeasurements',
            new_name='UnitOfMeasurements',
        ),
        migrations.RemoveField(
            model_name='product',
            name='description',
        ),
        migrations.RemoveField(
            model_name='product',
            name='price',
        ),
        migrations.RemoveField(
            model_name='purchaseitem',
            name='received_quantity',
        ),
        migrations.AlterField(
            model_name='purchaseitem',
            name='quantity',
            field=models.IntegerField(default=0),
        ),
    ]
