# Generated by Django 5.0.6 on 2024-07-17 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("purchases", "0003_paymentmade_paymentreceived_delete_payment"),
    ]

    operations = [
        migrations.AddField(
            model_name="unitofmeasurements",
            name="field",
            field=models.CharField(
                blank=True,
                choices=[("number", "number"), ("float", "float")],
                max_length=255,
                null=True,
            ),
        ),
    ]
