# Generated by Django 5.0.6 on 2024-07-18 15:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("purchases", "0005_alter_unitofmeasurements_field"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="paymentreceived",
            name="customer",
        ),
        migrations.RemoveField(
            model_name="order",
            name="customer",
        ),
        migrations.RemoveField(
            model_name="invoice",
            name="order",
        ),
        migrations.RemoveField(
            model_name="invoice",
            name="tenant",
        ),
        migrations.RemoveField(
            model_name="order",
            name="tenant",
        ),
        migrations.RemoveField(
            model_name="orderitem",
            name="order",
        ),
        migrations.RemoveField(
            model_name="paymentreceived",
            name="order",
        ),
        migrations.RemoveField(
            model_name="orderitem",
            name="product",
        ),
        migrations.RemoveField(
            model_name="orderitem",
            name="tenant",
        ),
        migrations.RemoveField(
            model_name="paymentreceived",
            name="tenant",
        ),
        migrations.DeleteModel(
            name="Customer",
        ),
        migrations.DeleteModel(
            name="Invoice",
        ),
        migrations.DeleteModel(
            name="Order",
        ),
        migrations.DeleteModel(
            name="OrderItem",
        ),
        migrations.DeleteModel(
            name="PaymentReceived",
        ),
    ]
