# Generated by Django 5.0.6 on 2024-07-29 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0007_product_opening_stock'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='opening_stock',
            field=models.IntegerField(null=True),
        ),
    ]
