# Generated by Django 5.0.6 on 2024-08-11 18:04

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0011_purchaseinovice_order_date'),
        ('tenant', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PurchaseInovice',
            new_name='PurchaseInvoice',
        ),
    ]
