version: '3.8'

services:
  django:
    build: .
    command: gunicorn core.wsgi:application -w 2 -b :8000 --timeout 120
    volumes:
      - ./src:/app
    ports:
      - "8000:8000"
    depends_on:
      - postgres
      - redis
      - celery
    env_file:
      - ./src/core/.env

  postgres:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data

    env_file:
      - ./src/core/.env

    environment:
      - POSTGRES_USER=hello_django
      - POSTGRES_PASSWORD=hello_django
      - POSTGRES_DB=hello_django

  redis:
    image: redis:6
    ports:
      - "6379:6379"

  celery:
    build: .
    command: celery -A core worker --loglevel=info
    volumes:
      - ./src:/app
    depends_on:
      - postgres
      - redis
    env_file:
      - ./src/core/.env

  celery_beat:
    build: .
    command: celery -A core beat --loglevel=info
    volumes:
      - ./src:/app
    depends_on:
      - postgres
      - redis
    env_file:
      - ./src/core/.env

volumes:
  postgres_data:
