# Generated by Django 5.1.1 on 2024-09-21 16:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
        ('tenant', '0002_tenantmodel_api_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='tenant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_instances', to='tenant.tenantmodel'),
        ),
    ]
