CREATE TABLE IF NOT EXISTS "purchases_paymentmade" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "created_at" datetime NOT NULL, "updated_at" date NOT NULL, "amount" decimal NOT NULL, "payment_method" varchar(50) NOT NULL, "payment_date" datetime NOT NULL, "transaction_id" varchar(50) NOT NULL UNIQUE, "supplier_id" bigint NOT NULL REFERENCES "purchases_supplier" ("id") DEFERRABLE INITIALLY DEFERRED, "tenant_id" bigint NULL REFERENCES "tenant_tenantmodel" ("id") DEFERRABLE INITIALLY DEFERRED, "created_by_id" bigint NULL REFERENCES "users_customuser" ("id") DEFERRABLE INITIALLY DEFERRED);

CREATE TABLE IF NOT EXISTS "sales_customer" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "created_at" datetime NOT NULL, "updated_at" date NOT NULL, "first_name" varchar(50) NOT NULL, "last_name" varchar(50) NOT NULL, "email" varchar(254) NOT NULL UNIQUE, "phone_number" varchar(15) NULL, "address" text NULL, "tenant_id" bigint NULL REFERENCES "tenant_tenantmodel" ("id") DEFERRABLE INITIALLY DEFERRED, "created_by_id" bigint NULL REFERENCES "users_customuser" ("id") DEFERRABLE INITIALLY DEFERRED);

CREATE TABLE IF NOT EXISTS "sales_salesitem" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "created_at" datetime NOT NULL, "updated_at" date NOT NULL, "quantity" integer NOT NULL, "price" decimal NOT NULL, "vat" integer NOT NULL, "vat_amount" decimal GENERATED ALWAYS AS ((CAST(((CAST(((CAST(("price" * "quantity") AS NUMERIC)) * "vat") AS NUMERIC)) / 100) AS NUMERIC))) STORED, "product_id" bigint NOT NULL REFERENCES "purchases_product" ("id") DEFERRABLE INITIALLY DEFERRED, "sales_id" bigint NOT NULL REFERENCES "sales_sales" ("id") DEFERRABLE INITIALLY DEFERRED, "tenant_id" bigint NULL REFERENCES "tenant_tenantmodel" ("id") DEFERRABLE INITIALLY DEFERRED, "stock_snapshot" integer NULL, "created_by_id" bigint NULL REFERENCES "users_customuser" ("id") DEFERRABLE INITIALLY DEFERRED);



CREATE TABLE IF NOT EXISTS "sales_salesinvoice" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "created_at" datetime NOT NULL, "updated_at" date NOT NULL, "billing_address" text NOT NULL, "total_amount" decimal NOT NULL, "payment_status" varchar(20) NOT NULL, "tenant_id" bigint NULL REFERENCES "tenant_tenantmodel" ("id") DEFERRABLE INITIALLY DEFERRED, "sales_id" bigint NOT NULL UNIQUE REFERENCES "sales_sales" ("id") DEFERRABLE INITIALLY DEFERRED, "created_by_id" bigint NULL REFERENCES "users_customuser" ("id") DEFERRABLE INITIALLY DEFERRED);


CREATE TABLE IF NOT EXISTS "purchases_product" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "created_at" datetime NOT NULL, "updated_at" date NOT NULL, "name" varchar(100) NOT NULL, "sku" varchar(50) NOT NULL UNIQUE, "tenant_id" bigint NULL REFERENCES "tenant_tenantmodel" ("id") DEFERRABLE INITIALLY DEFERRED, "uom_id" bigint NULL REFERENCES "purchases_unitofmeasurements" ("id") DEFERRABLE INITIALLY DEFERRED, "opening_stock" integer NULL, "stock_quantity" real NULL, "created_by_id" bigint NULL REFERENCES "users_customuser" ("id") DEFERRABLE INITIALLY DEFERRED);

CREATE TABLE IF NOT EXISTS "accounts_account" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "name" varchar(255) NOT NULL, "tenant_id" bigint NULL REFERENCES "tenant_tenantmodel" ("id") DEFERRABLE INITIALLY DEFERRED, "balance" decimal NOT NULL);

CREATE TABLE IF NOT EXISTS "accounts_bankaccount" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "name" varchar(255) NOT NULL, "tenant_id" bigint NULL REFERENCES "tenant_tenantmodel" ("id") DEFERRABLE INITIALLY DEFERRED, "accounttype" varchar(25) NOT NULL, "balance" decimal NOT NULL);

CREATE TABLE IF NOT EXISTS "accounts_cashaccount" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "name" varchar(255) NULL, "tenant_id" bigint NULL REFERENCES "tenant_tenantmodel" ("id") DEFERRABLE INITIALLY DEFERRED, "balance" decimal NOT NULL);

CREATE TABLE IF NOT EXISTS "purchases_purchaseitem" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "created_at" datetime NOT NULL, "updated_at" date NOT NULL, "quantity" integer NOT NULL, "price" decimal NOT NULL, "product_id" bigint NOT NULL REFERENCES "purchases_product" ("id") DEFERRABLE INITIALLY DEFERRED, "tenant_id" bigint NULL REFERENCES "tenant_tenantmodel" ("id") DEFERRABLE INITIALLY DEFERRED, "created_by_id" bigint NULL REFERENCES "users_customuser" ("id") DEFERRABLE INITIALLY DEFERRED, "purchase_id" bigint NOT NULL REFERENCES "purchases_purchaseinvoice" ("id") DEFERRABLE INITIALLY DEFERRED);

CREATE TABLE IF NOT EXISTS "sales_paymentreceived" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "created_at" datetime NOT NULL, "updated_at" date NOT NULL, "amount" decimal NOT NULL, "payment_method" varchar(50) NOT NULL, "payment_date" datetime NOT NULL, "customer_id" bigint NOT NULL REFERENCES "sales_customer" ("id") DEFERRABLE INITIALLY DEFERRED, "tenant_id" bigint NULL REFERENCES "tenant_tenantmodel" ("id") DEFERRABLE INITIALLY DEFERRED, "created_by_id" bigint NULL REFERENCES "users_customuser" ("id") DEFERRABLE INITIALLY DEFERRED, "transaction_id" varchar(100) NOT NULL);



CREATE TABLE IF NOT EXISTS "purchases_unitofmeasurements" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "created_at" datetime NOT NULL, "updated_at" date NOT NULL, "name" varchar(100) NOT NULL, "tenant_id" bigint NULL REFERENCES "tenant_tenantmodel" ("id") DEFERRABLE INITIALLY DEFERRED, "created_by_id" bigint NULL REFERENCES "users_customuser" ("id") DEFERRABLE INITIALLY DEFERRED, "field" varchar(255) NULL);


CREATE TABLE IF NOT EXISTS "purchases_purchasereturn" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "created_at" datetime NOT NULL, "updated_at" date NOT NULL, "return_date" datetime NOT NULL, "total_amount" decimal NOT NULL, "created_by_id" bigint NULL REFERENCES "users_customuser" ("id") DEFERRABLE INITIALLY DEFERRED, "purchase_invoice_id" bigint NOT NULL REFERENCES "purchases_purchaseinvoice" ("id") DEFERRABLE INITIALLY DEFERRED, "tenant_id" bigint NULL REFERENCES "tenant_tenantmodel" ("id") DEFERRABLE INITIALLY DEFERRED);
CREATE TABLE IF NOT EXISTS "purchases_purchasereturnitem" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "created_at" datetime NOT NULL, "updated_at" date NOT NULL, "quantity" integer NOT NULL, "price" decimal NOT NULL, "created_by_id" bigint NULL REFERENCES "users_customuser" ("id") DEFERRABLE INITIALLY DEFERRED, "product_id" bigint NOT NULL REFERENCES "purchases_product" ("id") DEFERRABLE INITIALLY DEFERRED, "purchase_return_id" bigint NOT NULL REFERENCES "purchases_purchasereturn" ("id") DEFERRABLE INITIALLY DEFERRED, "tenant_id" bigint NULL REFERENCES "tenant_tenantmodel" ("id") DEFERRABLE INITIALLY DEFERRED);

CREATE TABLE IF NOT EXISTS "purchases_stockmovement" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "created_at" datetime NOT NULL, "updated_at" date NOT NULL, "quantity" integer NOT NULL, "date" datetime NOT NULL, "description" text NULL, "product_id" bigint NOT NULL REFERENCES "purchases_product" ("id") DEFERRABLE INITIALLY DEFERRED, "tenant_id" bigint NULL REFERENCES "tenant_tenantmodel" ("id") DEFERRABLE INITIALLY DEFERRED, "created_by_id" bigint NULL REFERENCES "users_customuser" ("id") DEFERRABLE INITIALLY DEFERRED, "movement_type" varchar(20) NOT NULL);

CREATE TABLE IF NOT EXISTS "tenant_tenantmodel" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "name" varchar(255) NOT NULL UNIQUE, "domain" varchar(10) NOT NULL UNIQUE, "api_key" varchar(20) NULL UNIQUE);
CREATE TABLE IF NOT EXISTS "dashboard_message" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "room_name" varchar(255) NOT NULL, "content" text NOT NULL, "timestamp" datetime NOT NULL, "user_id" bigint NOT NULL REFERENCES "users_customuser" ("id") DEFERRABLE INITIALLY DEFERRED);

CREATE TABLE IF NOT EXISTS "django_tasks_database_dbtaskresult" ("id" char(32) NOT NULL PRIMARY KEY, "status" varchar(8) NOT NULL, "args_kwargs" text NOT NULL CHECK ((JSON_VALID("args_kwargs") OR "args_kwargs" IS NULL)), "priority" integer NOT NULL, "task_path" text NOT NULL, "queue_name" text NOT NULL, "backend_name" text NOT NULL, "run_after" datetime NULL, "result" text NULL CHECK ((JSON_VALID("result") OR "result" IS NULL)), "enqueued_at" datetime NOT NULL, "finished_at" datetime NULL, "started_at" datetime NULL, CONSTRAINT "priority_range" CHECK ("priority" BETWEEN -100 AND 100));
CREATE TABLE IF NOT EXISTS "purchases_purchaseinvoice" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "created_at" datetime NOT NULL, "updated_at" date NOT NULL, "invoice_number" varchar(100) NULL, "purchase_date" datetime NOT NULL, "total_amount" decimal NOT NULL, "received_date" datetime NULL, "tenant_id" bigint NULL REFERENCES "tenant_tenantmodel" ("id") DEFERRABLE INITIALLY DEFERRED, "supplier_id" bigint NOT NULL REFERENCES "purchases_supplier" ("id") DEFERRABLE INITIALLY DEFERRED, "created_by_id" bigint NULL REFERENCES "users_customuser" ("id") DEFERRABLE INITIALLY DEFERRED, "order_date" datetime NULL, "returned" bool NOT NULL);

CREATE TABLE IF NOT EXISTS "sales_sales" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "created_at" datetime NOT NULL, "updated_at" date NOT NULL, "total_amount" decimal NOT NULL, "customer_id" bigint NOT NULL REFERENCES "sales_customer" ("id") DEFERRABLE INITIALLY DEFERRED, "tenant_id" bigint NULL REFERENCES "tenant_tenantmodel" ("id") DEFERRABLE INITIALLY DEFERRED, "created_by_id" bigint NULL REFERENCES "users_customuser" ("id") DEFERRABLE INITIALLY DEFERRED, "returned" bool NOT NULL);

CREATE TABLE IF NOT EXISTS "sales_salesreturn" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "created_at" datetime NOT NULL, "updated_at" date NOT NULL, "created_by_id" bigint NULL REFERENCES "users_customuser" ("id") DEFERRABLE INITIALLY DEFERRED, "tenant_id" bigint NULL REFERENCES "tenant_tenantmodel" ("id") DEFERRABLE INITIALLY DEFERRED);
CREATE TABLE IF NOT EXISTS "sales_salesreturneditems" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "created_at" datetime NOT NULL, "updated_at" date NOT NULL, "created_by_id" bigint NULL REFERENCES "users_customuser" ("id") DEFERRABLE INITIALLY DEFERRED, "tenant_id" bigint NULL REFERENCES "tenant_tenantmodel" ("id") DEFERRABLE INITIALLY DEFERRED);

